export const ActionTypes = {
    FETCH_PRODCTS : "FETCH_PRODCTS",
    // SET_PRODUCTS : "SET_PRODUCTS",
    // SELECTED_PRODUCT : "SELECTED_PRODUCT",
    // REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    INCREMENT:"INCREMENT",DECREMENT:"DECREMENT"
};